### ISSUE TITLE
Task tree structure will be messed up with repeated task "terminal" names

### ISSUE THREAD

**Issue by dcecile** [go-task/vscode-task#110]
Result looks similar to #79, but this is caused by repeated "terminal" names. I have a root `build` and also nested `build`:

```yaml
version: '3'
tasks:
  build:
    cmd: echo build
  other:build:
    cmd: echo other build
```

![image](https://github.com/go-task/vscode-task/assets/311866/b8242ccb-734f-446a-b39b-2af93d45feef)

All of the nested repeats get duplicated into the root of the task tree view.

(Currently running v0.3.1)
