### ISSUE TITLE
Support ANSI colours in output window

### ISSUE THREAD

**Issue by apgrucza** [go-task/vscode-task#12]
Text in the output window should appear coloured if the task outputs ANSI escape codes that set the text colour.

For example:

```
tasks:
  colour:
    cmds:
      - echo -e "Add {{.RED}}new{{.NC}} feature"
    vars:
      RED: \033[1;31m
      NC: \033[0m
```

When this task is run via the extension, the text in the output window should appear as:

```ts
Add new feature
```

instead of:

```
Add [1;31mnew[0m feature
```
