### ISSUE TITLE
Running tasks from sidebar doesn't set the `{{.PWD}}` variable to the open folder's directory.

### ISSUE THREAD

**Issue by WinkelCode** [go-task/vscode-task#166]
Example:

```yml
version: "3"

tasks:
  default:
    cmds:
      - echo "{{.PWD}}"
```

Running from terminal:

```
$ task
task: [default] echo "/Volumes/Projects/Code_Projects/LinuxEnv"
/Volumes/Projects/Code_Projects/LinuxEnv
```

Running from sidebar:

```
task: [default] echo "/"
/
task: completed with code 0
```

The most logical behavior would be to set the PWD to the root of the opened folder.

---

- Task version:
```
$ task --version
Task version: 3.39.2 ()
```
- Operating System: macOS 15.1
