### ISSUE TITLE
Tasks with label: "does not exist"

### ISSUE THREAD

**Issue by gomes42** [go-task/vscode-task#167]
- Task version: v3.39.0 (h1:Loe6ppP1x38Puv1M2wigp91bH/garCt0vLWkJsiTWNI=)
- Operating System: Windows 11

### Taskfile.yml
```yml
version: '3'

tasks:
  # 1
  hello-with-label:
    label: "Hello World 🌎"
    desc: Print Hello World
    cmds:
      - echo "Hello World"

  # 2
  hello-without-label:
    desc: Print Hello World
    cmds:
      - echo "Hello World"
```

![Image](https://github.com/user-attachments/assets/edf024cf-23b9-41d1-8adc-82bfe1d23269)

`#1` OUTPUT `ERROR ❌`
```
task: Available tasks for this project:
* hello-with-label:          Print Hello World
* hello-without-label:       Print Hello World
task: Task "Hello World 🌎" does not exist
task: completed with code 200
```

`#2` OUTPUT `OK ✅`
```
task: [hello-without-label] echo "Hello World"
Hello World
task: completed with code 0
```
