### ISSUE TITLE
Task tree structure will be messed up when using multiple level of namespaces

### ISSUE THREAD

**Issue by I73v** [go-task/vscode-task#79]
<details>
<summary>Taskfile.yml</summary>

```YAML
---
version: "3"

tasks:
  root_0:node_0:node_00:
    cmds:
      - echo "Hi"

  root_0:node_0:node_01:
    cmds:
      - echo "Hi"

  root_0:node_1:node_00:
    cmds:
      - echo "Hi"

  root_0:node_1:node_01:
    cmds:
      - echo "Hi"

  root_0:node_2:node_00:
    cmds:
      - echo "Hi"

  root_0:node_2:node_01:
    cmds:
      - echo "Hi"

  root_0:node_2:node_00:node000:
    cmds:
      - echo "Hi"

  root_0:node_2:node_00:node001:
    cmds:
      - echo "Hi"
```

</details>

![single-file](https://github.com/go-task/vscode-task/assets/6691715/0ba635dc-c937-4290-840b-e4316032138f)

It goes deeper the more you add

Versions:

- Task version: v3.27.1 (h1:cftsoOqUo7/pCdtO7fDa4HreXKDvbrRhfhhha8bH9xc=)
- Operating System: Windows 11, WSL: Ubuntu-22.04
